### PR TITLE
add RPi.GPIO to requirements

### PR DESCRIPTION
**Pull request by brennen**
We're looking to dispense with this, but in the meantime I think it's breaking a fair number of installs.

### CODE REVIEW

**Comment by ladyada** [comment]
hmm i think this will break on non-Pi's right? can you put a warning on the import instead?

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit-Retrogame/blob/master/joyBonnet.py#L24

**Comment by brennen** [comment]
I had that thought and tested on my desktop system - nothing seems to complain.  It presumably wouldn't _work_, but I don't think install is really platform limited?

**Comment by ladyada** [comment]
no idea. i am very bad at python packaging :D

**Comment by brennen** [comment]
With last couple of commits:  Probably Good Enough.

**Comment by ladyada** [comment]
seems good to me @dhalbert any thoughts?

**Comment by dhalbert** [comment]
If those changes work, then OK. I would suggest not suggesting `sudo pip` in general in those error messages. It's a bad idea because it can conflict with distribution-supplied packages.

**Comment by brennen** [comment]
@dhalbert yeah, going the route of requiring RPi.GPIO on arm6/7 vs. giving install instrux in an error message.  Should fix the problem and even if that's casting a bit of a broad net, I don't think having it installed on non-Pi devices does any harm.

**Pull request merged**
