### PR TITLE
Added support for Siemens Simatic IOT2050 Basic/Advanced

### PR DESCRIPTION
**Pull request by schnurma**
Hello,
I added support for GPIO, AIO, I2C, SPI, UART, PWM, NeoPixels for the Siemens Simatic [IOT2050 SBC](http://www.siemens.com/iot2050)

I added my MIT Licence Informations to the Files I heavily modified and for files with only few changes I extend the licence informatons  -> am65xx/pin.py ; am65xx/pwmout.py.

thanks
best regards
Martin Schnur

### CODE REVIEW

**Comment by schnurma** [comment]
Checks failed because of missing Value. After the Pull-Request [#249](https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/249) is accepted this should work.

**Error Message:**
File "/home/runner/work/Adafruit_Blinka/Adafruit_Blinka/src/board.py", line 280, in <module>
    elif board_id == ap_board.SIEMENS_SIMATIC_IOT2050_ADV:
AttributeError: module 'adafruit_platformdetect.constants.boards' has no attribute 'SIEMENS_SIMATIC_IOT2050_ADV'

Error: Process completed with exit code 2.

**Comment by makermelissa** [comment]
Yeah, https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/249 will need to be merged in first and a new platform detect release needs to be published, then I'll re-run the checks on this PR and it should pass. I'll let you know if there's anything that needs to be done on your end. :)

**Comment by schnurma** [comment]
Thanks for your fast response.
Tested it today, everything seems fine :)

best regards
Martin Schnur

**Comment by makermelissa** [comment]
Thank you for adding. It was done very well.

**Pull request merged**
