### PR TITLE
fix mcp2221 i2c scan

### PR DESCRIPTION
**Pull request by ladyada**
errors throw an exception, a little more elegant than trying to check status

### CODE REVIEW

**Comment by caternuson** [comment]
I guess I was lucky and never had this show up. Might it ever throw something other than a Runtime? Like maybe an OSError from something in the HID library?

**Comment by ladyada** [comment]
yeah only would happen during a scan() or if you didnt have the sensor connected

**Comment by caternuson** [comment]
Looks good then if you want the scan to complete. But might be OK to have an exception get thrown if nothing is connected? vs. just silently consuming and continuing? Not sure what the better behavior is.

**Comment by ladyada** [comment]
it'll still throw an exception if you try to connect to a device address that isnt responding, it just wont do that during scanning

**Pull request merged**
