### PR TITLE
Partial work for adding hifive unleashed to Blinka

### PR DESCRIPTION
**Pull request by fede2cr**
Pins from page 25.

https://sifive.cdn.prismic.io/sifive%2Ffa3a584a-a02f-4fda-b758-a2def05f49f9_hifive-unleashed-getting-started-guide-v1p1.pdf

### CODE REVIEW

**Comment by makermelissa** [comment]
Hi, I'm not sure if you were already planning to do so, be we normally have separate microcontroller and board files so that if multiple boards use the same microcontroller it's easy to add the new board.

**Comment by fede2cr** [comment]
AFAIK, the microcontroller is not available as a separate device, only included in the HFU processor.
The pins are in microcontoller/ as I was not sure where would be a good place to do it.

**Comment by makermelissa** [comment]
Ok, so the board is really just an abstraction of the microcontroller. Think of the microcontroller as defining the functions that the MCU can do and the board as a way to route which microcontroller pin to which GPIO pin. That way it can be reconfigured very easily.

For instance, let's say we have two boards that use the exact same microcontroller, but the GPIO pins on the header are arranged differently. We can use the same microcontroller file, but have different board files to tell which microcontroller pin goes to which GPIO header pin.

So we define all the pins in microcontroller and then define the board by pointing to the defined pins inside of the microcontroller you defined. Since you already have the pins figured out, you have a lot of the hard stuff done. You can take a look at how I did the dragonboard 410c as an example.

**Comment by fede2cr** [comment]
Does this look ok?

**Comment by makermelissa** [comment]
Almost. Make sure you are also checking for the board/microcontroller in these files:
`src/busio.py`
`src/digitalio.py`
`src/microcontroller/pin.py`
`src/microcontroller/__init__.py`

**Comment by makermelissa** [comment]
Hi, just wanted to check in with you since you're like 98% done.

**Comment by makermelissa** [comment]
Not sure why it auto closed... Was trying to squash new commits, but too many working pieces probably.

**Comment by makermelissa** [comment]
Looks like I have the correct file changes captured on a branch, so I'll just do this from my repo.

**Comment by makermelissa** [comment]
I can't re-open this, so I continued it in #220.

**Pull request closed without merging**
