### PR TITLE
add I2C and SPI singletons for some drivers

### PR DESCRIPTION
**Pull request by ladyada**
will default to the names we have for I2C and SPI default pins

### CODE REVIEW

**Comment by ladyada** [comment]
ok - it was tested on a raspi

**Comment by ladyada** [comment]
please bump a release and you can reply/close the issue

**Comment by kattni** [comment]
Will do!

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_CircuitPython_ServoKit/issues/7#issuecomment-475596473
as well

**Pull request merged**
