### PR TITLE
I2C implementation of USB_ISS board 

### PR DESCRIPTION
**Pull request by FelixRoh**
I2C implementation of one of the fastest USB to I2C connections moduls:
Hardware reference: https://www.robot-electronics.co.uk/htm/usb_iss_tech.htm
PIP Package: https://pypi.org/project/usb-iss/

### CODE REVIEW

**Review by FelixRoh — COMMENTED** [review]
Corrections based on pylint feedback

**Comment by FelixRoh** [comment]
Whats wrong? Why something is skipped?

**Comment by makermelissa** [comment]
> Whats wrong? Why something is skipped?

It looks like you need to run pre-commit. See https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code.

**Comment by makermelissa** [comment]
Closing for now. Please re-open when it's ready.

**Pull request closed without merging**
