### PR TITLE
FT232H: save i2c instance in Pin

### PR DESCRIPTION
**Pull request by thijstriemstra**
refs #389

### CODE REVIEW

**Comment by tannewt** [comment]
@caternuson could this init be done on import rather than first construction?

**Comment by caternuson** [comment]
As I remember it, there's some weirdness because GPIO access is done through either the I2C or SPI controller. So I2C and SPI do some shenanigans as result.
https://github.com/adafruit/Adafruit_Blinka/blob/e0d98bdea5b0323b1ec9568d43c32d57744cde8f/src/adafruit_blinka/microcontroller/ft232h/i2c.py#L17
https://github.com/adafruit/Adafruit_Blinka/blob/e0d98bdea5b0323b1ec9568d43c32d57744cde8f/src/adafruit_blinka/microcontroller/ft232h/spi.py#L23

But maybe there's a different way to do that which could also address #389.

**Comment by caternuson** [comment]
@thijstriemstra Is this code working for you to get you around issue #389 for your use case?

**Comment by thijstriemstra** [comment]
@caternuson yep, I use it like this:

```python
board.C0.i2c.configure("ftdi:///1")
```

it's not pretty but it works. See #389 for more details.

**Comment by thijstriemstra** [comment]
ps. maybe `ft232h_i2c` would be a better name?

**Comment by caternuson** [comment]
My notional thinking/hope was that something like `UsbTools.flush_cache()` could somehow get used automatically in here to recover after being hot plugged. So nothing would have to change in user code. At least that's the hope.

**Comment by thijstriemstra** [comment]
Is this PR acceptable or anything I can change?

**Comment by caternuson** [comment]
The only change would be to run black on `pin.py`. Looks like some trailing white space got introduced and it's causing the CI to fail.

BUT - This PR may not be the best approach. This approach gives you easy access to the underlying FT232H plumbing, but it still requires (as I understand it) that you do something like
```python
board.C0.i2c.configure("ftdi:///1")
```
in your code. I'd be better if we could find a way to do the same thing, but more internally to the library.

**Comment by thijstriemstra** [comment]
Removed the whitespace.

I wouldn't mind placing the code elsewhere but I'm not familiar with overall architecture of this package. Maybe it can be a follow up PR.

**Comment by thijstriemstra** [comment]
Fixed merge conflict with new package structure.

**Comment by makermelissa** [comment]
You may want to pull in the latest changes, which will pin PyLint to an older version and some (maybe all) of the failed checks should go away.

**Comment by thijstriemstra** [comment]
> You may want to pull in the latest changes, which will pin PyLint to an older version and some (maybe all) of the failed checks should go away.

Done.

**Comment by thijstriemstra** [comment]
Anything else I can do here?

**Comment by makermelissa** [comment]
I think we're just waiting on @caternuson to review it again.

**Comment by caternuson** [comment]
@thijstriemstra Are you using SPI in any of your setups?

**Comment by thijstriemstra** [comment]
No.

**Comment by caternuson** [comment]
Looks like maybe you're not even using I2C? Just GPIO. (based on issue thread).

Have you tried accessing the controller via either I2C or SPI? Those classes do store the controller. So instead of:
```python
board.C0.i2c.configure("ftdi:///1")
```
could do this:
```python
# grab an I2C instance in the normal way
i2c = board.I2C()

# to access the I2cController instance and call configure:
i2c._i2c.configure("ftdi:///1")
```
Even if you don't actually use I2C for anything.

Sorry this PR has been open for so long. My general concern is that this change might break other things in subtle ways.  The use of I2C in the Pin class was just a random choice. It could also have been SPI.

**Comment by thijstriemstra** [comment]
> My general concern is that this change might break other things in subtle ways. The use of I2C in the Pin class was just a random choice. It could also have been SPI.

If there's a better way, like one you suggested, I will give it a try. To be continued.. (in #389)

**Comment by makermelissa** [comment]
@caternuson this PR is pretty old. Are we waiting on something to be able to merge or should we just close it until it's ready?

**Comment by caternuson** [comment]
I think this PR is as ready as it's going to be. It's generally OK in terms of CI, etc. But still concerned about the general approach. The original issue in #389 was only using I2C. The FT232H is a bit weird in how GPIO is accessed thru *either* the I2C or SPI controller ([see comment above](https://github.com/adafruit/Adafruit_Blinka/pull/417#issuecomment-776240865)). And only one should be used at any given time (the FT232H can not do SPI and I2C at the same time). So for someone doing something similar, but using SPI, there still may be an issue.

The general issue is dealing with hot swapping. There's more discussion in the #389 issue thread. Unfortunately, none of the other options discussed there seemed to work. :(

@makermelissa I suggest we close both #417 and #389 for now. Dealing with hot swapping USB is tricky.

@thijstriemstra Thanks for this PR and all the discussion. This code modification seems to have worked to fix your specific issue, so simple solution in your case is to continue using it.

These discussions threads will always be here for general reference.

**Comment by makermelissa** [comment]
Ok @caternuson. I'm fine with closing those issues. I'm still a bit unclear about if you want to merge this PR or just close it.

**Comment by caternuson** [comment]
Closing for now. Not sure best general solution for this at this time.

**Comment by makermelissa** [comment]
Oh, gotcha. I didn't notice this PR was #417.

**Pull request closed without merging**
