### PR TITLE
Update orangepi4 board

### PR DESCRIPTION
**Pull request by AYastrebov**
In this pull request I have updated pinout for OrangePi4 board.
In the previous PR (https://github.com/adafruit/Adafruit_Blinka/pull/612) the pinout was incorrect

### CODE REVIEW

**Comment by makermelissa** [comment]
@twa127 since you know the Orange Pi boards better than I do and added the board originally, could you confirm that it has changed or is it a similar board? Thanks.

**Comment by makermelissa** [comment]
Never mind, I see you had previously responded here: https://github.com/adafruit/Adafruit_Blinka/pull/612#issuecomment-1422429204

**Review by makermelissa — APPROVED** [review]
Thanks, looks good.

**Comment by twa127** [comment]
He he was just about to reply, hope all is well with you Sent from my iPhoneOn 22 Feb 2023, at 15:53, Melissa LeBlanc-Williams ***@***.***> wrote:﻿
Merged #653 into main.

**Pull request merged**
