### PR TITLE
Add Binho Nova integration

### PR DESCRIPTION
**Pull request by fig1010**

### CODE REVIEW

**Comment by ladyada** [comment]
wow - epic PR! I saw I2C and SPI are tested - and y'all have tested GPIO (out, in, pullups/pulldowns), PWM with various frequencies/duty cycle?

**Comment by fig1010** [comment]
> wow - epic PR! I saw I2C and SPI are tested - and y'all have tested GPIO (out, in, pullups/pulldowns), PWM with various frequencies/duty cycle?

PWM was tested with sample code found on one of your example pages:

`import time
import board
import pulseio

led = pulseio.PWMOut(board.IO0, frequency=5000, duty_cycle=0)

while True:
    for i in range(100):
        # PWM LED up and down
        if i < 50:
            led.duty_cycle = int(i * 2 * 65535 / 100)  # Up
        else:
            led.duty_cycle = 65535 - int((i - 50) * 2 * 65535 / 100)  # Down
        time.sleep(0.01)`

GPIO's were tested as well, however currently pullups/pulldowns are not supported in GPIO mode.  We will be supporting it on our next FW update. However, in I2C mode, we do engage external pullup resistors.

Basic GPIO test code used, GPIO also tested as part of SPI bme280 example as that configures a chip select pin for SPI interface:

`import board
import digitalio
 
led = digitalio.DigitalInOut(board.IO0)
led.direction = digitalio.Direction.OUTPUT
led.value = True
print(led.value)
led.value = False
print(led.value)`

**Comment by makermelissa** [comment]
Hi, could you please rebase? There were a couple PRs that were in the queue ahead of this one and I have merged them in. Thanks

**Comment by fig1010** [comment]
> Hi, could you please rebase? There were a couple PRs that were in the queue ahead of this one and I have merged them in. Thanks

Will do.

**Comment by fig1010** [comment]
> Hi, could you please rebase? There were a couple PRs that were in the queue ahead of this one and I have merged them in. Thanks

Completed the rebase.

**Comment by makermelissa** [comment]
After PlatformDetect gets pushed up to PyPI, this should start passing the Travis checks.

**Comment by ladyada** [comment]
yay! @makermelissa please work together to get into circuitpython.org :) :) :)

**Comment by fig1010** [comment]
Very exciting!  Thanks @makermelissa & @ladyada!! Can't wait to get folks using Binho Nova! :)

**Comment by ladyada** [comment]
@fig1010 yay yep they can start immediately - do y'all want to write a learning guide like the style we have here?

https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h
https://learn.adafruit.com/circuitpython-on-raspberrypi-linux
https://learn.adafruit.com/circuitpython-on-orangepi-linux

or we can point people to your guide!

**Comment by fig1010** [comment]
@ladyada We're currently working on a guide for our support page and should be able to complete it in the next couple of days. But we would also love to have a learning guide at learn.adafruit.com similar to the ones you pointed to, perhaps a basic setup and example to get them going and point to our page for more support.  We'll share our guide as soon as it's ready with you and would be happy to help with whatever we can to make it fit to your format for your learn.adafruit.com website.  Let us know if this sounds good and if there's anything else we can or should do.  Thank you!

**Comment by ladyada** [comment]
yes! sounds good, @TheKitty can get you set up on learn :)

**Comment by francisguevarra** [comment]
@ladyada @TheKitty 
here's our Binho Nova Adafruit guide document:
https://docs.google.com/document/d/1_KxgWQ1YNU7bfeLbRX8GJmxkME-USPIKdvWWkjgaKSo/edit?usp=sharing
here's where we saved the assets (images and animations) from the guide:
https://drive.google.com/drive/folders/1fwR4YuGhTs0hcl8_bJl1YX-u9sXRwzbY?usp=sharing

And here's our version of it in our support site:
https://support.binho.io/learn-and-grow/binho-+-circuitpython

Please let me know if you have any questions or if we can help in any way.

**Comment by ladyada** [comment]
yay rad!
1) would you be interested in re-publishing that content on learn.adafruit.com?
2) what are the most popular device drivers you see people using/wanting with the binho

**Comment by fig1010** [comment]
> yay rad!
> 
> 1. would you be interested in re-publishing that content on learn.adafruit.com?
> 2. what are the most popular device drivers you see people using/wanting with the binho

1. Yes we would, that would be awesome!
2. Binho is great for any of the stemma QT, qwiic, or Feather form-factor sensor boards.  Here's a small list that we came up with that we think would be good to use with a binho:
https://drive.google.com/open?id=13haqf0hvdEqbYd5vNmoIGt2EFjEpyZK8-A_NRoFtgZg

**Comment by ladyada** [comment]
@fig1010 hiya that docs link is not readable, please make it world-readable, or paste here?
please email anne@adafruit.com to get set up with a learn account

**Comment by fig1010** [comment]
https://docs.google.com/document/d/13haqf0hvdEqbYd5vNmoIGt2EFjEpyZK8-A_NRoFtgZg/edit?usp=sharing

> @fig1010 hiya that docs link is not readable, please make it world-readable, or paste here?
> please email [anne@adafruit.com](mailto:anne@adafruit.com) to get set up with a learn account

Sorry about that, just made the link world readable.  And will send out email with regards to getting started with learn account.

**Comment by fig1010** [comment]
@ladyada the email to anne@adafruit.com bounced back and looks to be invalid.

**Comment by ladyada** [comment]
sorry my bad - meant `anneb`!

**Pull request merged**
