### PR TITLE
Add Support for Orangepi 4

### PR DESCRIPTION
**Pull request by twa127**

### CODE REVIEW

**Review by makermelissa — APPROVED** [review]
Looks good. Thanks.

**Comment by AYastrebov** [comment]
Hi @twa127, thanks for your contribution.

I'am also using Orange Pi 4 and have a question about your PR.
Are you sure that the pins mapping in [orangepi4.py](https://github.com/twa127/Adafruit_Blinka/commit/85c803b81df1598d97784f8f9b63f4d9554d227d#diff-3f630c2b589dd2ec821ab9404ab4cacb64cc57f8108d9d4bbb2f8d2c5f279806) is done correct?

I see some mismatch when compare to board [pinout](https://service.robots.org.nz/wiki/Wiki.jsp?page=OrangePi) and the output of `gpio readall`

image

**Comment by twa127** [comment]
Hi,You are correct, do you want to write a pin mapping or do you want me to do it?Regards TerrySent from my iPhoneOn 7 Feb 2023, at 23:11, Andrey Yastrebov ***@***.***> wrote:﻿
Hi @twa127, thanks for your contribution.
I'am also using Orange Pi 4 and have a question about your PR.
Are you sure that the pins mapping in orangepi4.py is done correct?
I see some mismatch when compare to board pinout and the output of gpio readall

**Comment by AYastrebov** [comment]
Ok, I'll make pin mapping myself and open pull request, thanks!

**Comment by twa127** [comment]
ThanksSent from my iPhoneOn 9 Feb 2023, at 11:54, Andrey Yastrebov ***@***.***> wrote:﻿
Ok, I'll make pin mapping myself and open pull request, thanks!

**Pull request merged**
