### PR TITLE
updated error message for board.py where board_id is None, providing …

### PR DESCRIPTION
**Pull request by arhyneRWU**
…a message that helps users remember to upgrade their packages to the lastest verison.  This error is likely a result of new hardware on older code bases. Solutions were not easily found.

### CODE REVIEW

**Comment by makermelissa** [comment]
Could you change it to read more like this? Thanks.
```
raise NotImplementedError("{0} version {1} was unable to identify the board and/or microcontroller running the "
                          "{2} platform. Please be sure you have the latest packages running: 'pip3 install --upgrade "
                          "adafruit-blinka adafruit-platformdetect'".format(package[0],package[1], platform.system()))
```

**Comment by arhyneRWU** [comment]
> Could you change it to read more like this?
> 
> Adafruit-PlatformDetect version 3.4.1.dev4+g8a40e3d was unable to identify the board and/or microcontroller running the Darwin platform. Please be sure you have the latest packages running: 'pip3 install --upgrade adafruit-blinka adafruit-platformdetect'
> 
> Thanks.
> 
> ```
> raise NotImplementedError("{0} version {1} was unable to identify the board and/or microcontroller running the "
>                           "{2} platform. Please be sure you have the latest packages running: 'pip3 install --upgrade "
>                           "adafruit-blinka adafruit-platformdetect'".format(package[0],package[1], platform.system()))
> ```

Thanks, hope that looks better.

**Comment by makermelissa** [comment]
Whoops, looks like you need to run black first, which can be installed with pip.

**Review by makermelissa — APPROVED** [review]
Thanks!

**Pull request merged**
