### PR TITLE
Fix pin number assignment for allwinner h616

### PR DESCRIPTION
**Pull request by lz00qs**
Link to https://github.com/adafruit/Adafruit_Blinka/issues/689

Modify the format of the pin parameter to fix errors bellow:

```
Traceback (most recent call last):
  File "/root/oled.py", line 13, in <module>
    btn = DigitalInOut(board.PC11)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/digitalio.py", line 183, in __init__
    self.direction = Direction.INPUT
    ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/digitalio.py", line 213, in direction
    self._pin.init(mode=[Pin.IN](http://pin.in/))
  File "/usr/lib/python3.11/site-packages/adafruit_blinka/microcontroller/generic_linux/libgpiod_pin.py", line 56, in init
    self._line = self._chip.get_line(int(self._num))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
```

Tested on orange pi zero2, archlinux, 6.1.31 orange pi official kernel.

### CODE REVIEW

**Comment by makermelissa** [comment]
@twa127 since you originally added this board, do you know if something changed on the board or could it be an OS-specific thing?

**Comment by twa127** [comment]
Away from home until 15th Dec, will respond when I get back.

**Comment by makermelissa** [comment]
> Away from home until 15th Dec, will respond when I get back.

No worries. Thank you. 🙏

**Comment by lz00qs** [comment]
Any updates on this request?

**Comment by makermelissa** [comment]
@twa127 have you had a chance to look at this?

**Comment by twa127** [comment]
Very sorry for the delay in getting back to you.

I am no longer using the OrangePi Zero 2 but have tested this change on my old board which is running 'Orange Pi buster with Linux 4.9.170-sun50iw9' and this proposed change does not run. The error message is as follows:

Traceback (most recent call last):
  File "/var/www/cron/gpio_relay_test.py", line 64, in <module>
    main()
  File "/var/www/cron/gpio_relay_test.py", line 53, in main
    relay = digitalio.DigitalInOut(getattr(board, pin_num))
  File "/usr/local/lib/python3.7/dist-packages/digitalio.py", line 143, in __init__
    self.direction = Direction.INPUT
  File "/usr/local/lib/python3.7/dist-packages/digitalio.py", line 173, in direction
    self._pin.init(mode=Pin.IN)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_blinka/microcontroller/generic_linux/libgpiod_pin.py", line 46, in init
    self._line = self._chip.get_line(int(self._num))
OSError: [Errno 22] Invalid argument

The existing version of pin.py does continue to work on my version of the OS

**Comment by makermelissa** [comment]
> I wonder if this user is using the OrangePi OS rather than Debian or Ubuntu and perhaps that is an issue.

I believe that is the case. They say they have archlinux, 6.1.31 orange pi official kernel. Thanks for your input @twa127.

**Comment by twa127** [comment]
Hi, I've managed to install Armbian Bookworm on my OPi Zero2
root@orangepizero2:/# uname -r
6.6.16-current-sunxi64

I get exactly the same results, ie. runs okay with existing version, fails with the proposed new version

**Comment by twa127** [comment]
I've done a bit more testing and have installed the OPios which is based on ArchLinux. I cannot successfully install Blinka as the package manager (pacman) does not appear to work in this image and hence I cannot load the prerequisites. I would have not expected Blinka to function without perhaps some work in PlatformDetect.

**Comment by makermelissa** [comment]
Thanks for testing @twa127. @lz00qs how were you able to get it running?

**Comment by lz00qs** [comment]
> Thanks for testing @twa127. @lz00qs how were you able to get it running?

Also Thanks for testing @twa127. On my system (archlinux, 6.1.31 kernel) I was able to solve the problem by using this modification, I think it might be a difference in the underlying bsp of the kernel that is causing the problem, I'm on a business trip right now and it might take me as long as April to verify the problem. When I get back, I'll verify the issue with the official orange pi os 4.4, 5.4 and 6.1 kernels.

**Comment by twa127** [comment]
Hi, Did a bit more testing and was able to get OPios installed and pacman working, installed libgpiod and pip3, used pip3 to install Blinka. As in the previous case the existing pin.py worked okay and the modified version failed.

I tested using Python3 as below:

>>> import board, digitalio 
>>> relay = digitalio.DigitalInOut(getattr(board, 'PC15'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/digitalio.py", line 187, in __init__
    self.direction = Direction.INPUT
    ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/digitalio.py", line 217, in direction
    self._pin.init(mode=Pin.IN)
  File "/usr/lib/python3.11/site-packages/adafruit_blinka/microcontroller/generic_linux/libgpiod/libgpiod_pin_2_x.py", line 52, in init
    config={int(self._num): None},
                ^^^^^^^^^
AttributeError: 'Pin' object has no attribute '_num'

**Comment by lz00qs** [comment]
> Hi, Did a bit more testing and was able to get OPios installed and pacman working, installed libgpiod and pip3, used pip3 to install Blinka. As in the previous case the existing pin.py worked okay and the modified version failed.
> 
> I tested using Python3 as below:
> 
> > > > import board, digitalio
> > > > relay = digitalio.DigitalInOut(getattr(board, 'PC15'))
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/usr/lib/python3.11/site-packages/digitalio.py", line 187, in **init**
> > > > self.direction = Direction.INPUT
> > > > ^^^^^^^^^^^^^^
> > > > File "/usr/lib/python3.11/site-packages/digitalio.py", line 217, in direction
> > > > self._pin.init(mode=Pin.IN)
> > > > File "/usr/lib/python3.11/site-packages/adafruit_blinka/microcontroller/generic_linux/libgpiod/libgpiod_pin_2_x.py", line 52, in init
> > > > config={int(self._num): None},
> > > > ^^^^^^^^^
> > > > AttributeError: 'Pin' object has no attribute '_num'

Thank you for your further testing, could you please provide the kernel version you are running? Could you please test this issue on 6.1 kernel?

**Comment by twa127** [comment]
[root@orange-os /]# uname -r
6.1.31-1+

**Comment by twa127** [comment]
Using the existing pin.py

>>> import board, digitalio
>>> relay = digitalio.DigitalInOut(getattr(board, 'PC15'))
>>> relay.direction = digitalio.Direction.OUTPUT
>>> relay.value = True
>>> relay.value = False
>>>

**Comment by twa127** [comment]
I installed Blinka using

pip3 install --break-system-packages adafruit-blinka

**Comment by twa127** [comment]
I tried your btn = digitalio.DigitalInOut(board.PC11) on both the existing and modified versions of pin.py, again worked for the existing and failed with the modified.

**Comment by twa127** [comment]
The reason why I used the format 'PC11 = Pin((1, 75))' is that if you run gpiodetect it gives
[root@orange-os h616]# gpiodetect
gpiochip0 [7022000.pinctrl] (32 lines)
gpiochip1 [300b000.pinctrl] (288 lines)

ie. there are 2 gpio devices on the chip, so need to distinguish between them as per the guide at https://learn.adafruit.com/adding-a-single-board-computer-to-blinka/adding-the-chip-file

**Comment by lz00qs** [comment]
> The reason why I used the format 'PC11 = Pin((1, 75))' is that if you run gpiodetect it gives [root@orange-os h616]# gpiodetect gpiochip0 [7022000.pinctrl] (32 lines) gpiochip1 [300b000.pinctrl] (288 lines)
> 
> ie. there are 2 gpio devices on the chip, so need to distinguish between them as per the guide at https://learn.adafruit.com/adding-a-single-board-computer-to-blinka/adding-the-chip-file

Thanks for all your reply, after I get back, I'll test it !

**Comment by makermelissa** [comment]
@lz00qs #830 submitted by @sc-bin found a clever solution. It's now been merged and released. Want to check that it works for you?

**Comment by lz00qs** [comment]
> @lz00qs #830 submitted by @sc-bin found a clever solution. It's now been merged and released. Want to check that it works for you?

yes it works for me, thanks @sc-bin, awsome job!

**Pull request closed without merging**
