### PR TITLE
Duplicate Beaglebone Black for Green Wireless

### PR DESCRIPTION
**Pull request by crbn60**
Implements #185.

As far as I can tell, the pinouts are nearly identical to the Beaglebone Back, so I just duplicated. As I learn more about how hardware works, I will come back and tweak the definition as required.

Please let me know if this is not as easy as I think it is.

### CODE REVIEW

**Comment by crbn60** [comment]
I concur with both you and will make the change.

I wasn't sure that was going to work as I'm not sure the board pinouts are actually identical, but I guess I can trip over that in the future as necessary.

**Comment by ladyada** [comment]
yayy! @makermelissa wanna add a downloads page entry some time this week?

**Comment by makermelissa** [comment]
Sure. I think there's a few others like the BBB and Beaglebone Pocket that we can add that just don't have guides yet.

**Comment by hulkco** [comment]
This is my recipe to make de BBGW run Blinka!!!
https://1drv.ms/o/s!Al-YhOt00we6zQbR8-qb3Zggbkqy
Sorry i made this in spanish 
:)

**Comment by makermelissa** [comment]
@hulkco, it's now released and part of Blinka, so you may need to update that guide. Also, if you pip install adafruit-blinka, it should install platformdetect as well as some other packages as dependencies.

**Pull request merged**
