### PR TITLE
Multibyteaddr

### PR DESCRIPTION
**Pull request by ladyada**
this is the part 2 to fix linux write-then-read :)

### CODE REVIEW

**Comment by ladyada** [comment]
yay this is great we can now talk to any device/sensor - there were a few with 16-bit addresses from before :) @makermelissa plz bump at your convenience

**Comment by caternuson** [comment]
I just tested this with a MCP9600 as a way to check if what used to **not** work now does. And it does!

With this PR:
```python
pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import board
>>> import adafruit_mcp9600
>>> mcp = adafruit_mcp9600.MCP9600(board.I2C())
>>> mcp.ambient_temperature
25.0625
>>> 
```

previously:
```python
pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import board
>>> import adafruit_mcp9600
>>> mcp = adafruit_mcp9600.MCP9600(board.I2C())
>>> mcp.ambient_temperature
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/blinka-test/lib/python3.7/site-packages/adafruit_mcp9600.py", line 293, in ambient_temperature
    data = self._read_register(_REGISTER_COLD_JUNCTION, 2)
  File "/home/pi/blinka-test/lib/python3.7/site-packages/adafruit_mcp9600.py", line 324, in _read_register
    in_start=1
  File "/home/pi/blinka-test/lib/python3.7/site-packages/adafruit_bus_device/i2c_device.py", line 150, in write_then_readinto
    in_start=in_start, in_end=in_end)
  File "/home/pi/blinka-test/lib/python3.7/site-packages/busio.py", line 87, in writeto_then_readfrom
    in_start=in_start, in_end=in_end, stop=stop)
  File "/home/pi/blinka-test/lib/python3.7/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 62, in writeto_then_readfrom
    raise NotImplementedError("Currently can only write a single byte in writeto_then_readfrom")
NotImplementedError: Currently can only write a single byte in writeto_then_readfrom
>>> 
```

**Comment by ladyada** [comment]
:) :) :) :)

**Comment by ladyada** [comment]
@kattni you can re-visit the MCP9600 guide nao!

**Pull request merged**
