### PR TITLE
Add BananaPi M1 board

### PR DESCRIPTION
**Pull request by not7cd**
Add support for http://www.banana-pi.org/m1.html

### CODE REVIEW

**Comment by not7cd** [comment]
I have found datasheets related to A20 microcontroller used on this board, but I'm not sure where to start. In other boards, a Pin object is created with numeric id.

https://linux-sunxi.org/A20

**Comment by cr1tbit** [comment]
https://linux-sunxi.org/GPIO

```
To obtain the correct number you have to calculate it from the pin name (like PH18):

(position of letter in alphabet - 1) * 32 + pin number
```

**Comment by makermelissa** [comment]
Hi, AllWinner chips tend to be very similar to each other. Maybe take a look at the AllWinner H3, A33,  or A64 that has already been added to start with. For that board, I would probably go with an Armbian/libgpiod combo, which is how we implemented the other AllWinner chips.

If you haven't seen the guides for adding board, check out https://learn.adafruit.com/adding-a-single-board-computer-to-platformdetect-for-blinka and https://learn.adafruit.com/adding-a-single-board-computer-to-blinka.

Also, this is a good resource:
https://www.beyondlogic.org/an-introduction-to-chardev-gpio-and-libgpiod-on-the-raspberry-pi/

**Comment by makermelissa** [comment]
Is this PR something that you're still interested in finishing?

**Comment by not7cd** [comment]
I will look into this in 1 or 2 months. I have quite intense time right now. But help will be welcome.

**Comment by makermelissa** [comment]
Ok, thanks for the quick response.

**Comment by makermelissa** [comment]
Hi, I'm going to close this PR for now. If you'd like to continue working on it, we can reopen.

**Comment by not7cd** [comment]
I'm alright with this. Unfortunately I don't need GPIO in Banana Pi in my current project. But I might revisit this, when time allows.

**Comment by rlesac** [comment]
One more vote for the implementation. I see that Banana Pi M2 zero support has been added, it might help with the M1 board.

**Pull request closed without merging**
