### PR TITLE
Added SoPine compatibility

### PR DESCRIPTION
**Pull request by SecT0uch**
Introduce SoPine compatibility

### CODE REVIEW

**Comment by ladyada** [comment]
hihi can you run `black` on your pull? see
https://github.com/adafruit/Adafruit_Blinka/runs/1411437263

**Comment by SecT0uch** [comment]
> hihi can you run black on your pull?
Done :+1: 

Test is not passing because adafruit_platformdetect (in the tesy) doesn't contain my last commit

**Comment by makermelissa** [comment]
I just pushed a release of platformdetect that includes your changes and we can rerun the checks after that.

**Review by makermelissa — APPROVED** [review]
Looks great. Thanks

**Pull request merged**
