### PR TITLE
PocketBeagle support

### PR DESCRIPTION
**Pull request by s-light**
WIP

this pull request adds the definitions for the BeagleBoard [PocketBeagle](https://beagleboard.org/pocket)
more discussion about this can be found in #100 

includes changes from [BBB_pinFixes](https://github.com/s-light/Adafruit_Blinka/tree/BBB_pinFixes)

### CODE REVIEW

**Comment by s-light** [comment]
currently this is untested!!

**Comment by pdp7** [comment]
@s-light testing with a PocketBeagle board on your branch `PocketBeagle`, I encountered this error:
```
debian@beaglebone:~/pr/Adafruit_Blinka$ sudo python3 examples/bbb_digitalio.py 
Traceback (most recent call last):
  File "examples/bbb_digitalio.py", line 10, in <module>
    import board
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_Blinka-1.2.9.dev5+gcbfa2eb.d20190330-py3.5.egg/board.py", line 59, in <module>
    from adafruit_blinka.board.beaglebone_pocketbeagle import *
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_Blinka-1.2.9.dev5+gcbfa2eb.d20190330-py3.5.egg/adafruit_blinka/board/beaglebone_pocketbeagle.py", line 114, in <module>
    MOSI_1 = pin.P2_25
AttributeError: module 'adafruit_blinka.microcontroller.am335x.pin' has no attribute 'P2_25'
```

I think P2_25 might need to be added to src/adafruit_blinka/microcontroller/am335x/pin.py like:
```
P2_25 = Pin('P2_25')
```

**Comment by pdp7** [comment]
@s-light this change a seems to fix that error:
```diff
diff --git a/src/adafruit_blinka/microcontroller/am335x/pin.py b/src/adafruit_blinka/microcontroller/am335x/pin.py
index b07ad0f..71715e6 100644
--- a/src/adafruit_blinka/microcontroller/am335x/pin.py
+++ b/src/adafruit_blinka/microcontroller/am335x/pin.py
@@ -110,7 +110,7 @@ P2_20 = Pin('P2_20')
 P2_22 = Pin('P2_22')
 
 P2_24 = Pin('P2_24')
-
+P2_25 = Pin('P2_25')
 P2_26 = Pin('P2_26')
 P2_27 = Pin('P2_27')
 P2_28 = Pin('P2_28')
```


I have wired up an LED to P1.33 and this test blinks the LED okay:
```
import time
import board
import digitalio

print("hello blinky!")

led = digitalio.DigitalInOut(board.P1_33)
led.direction = digitalio.Direction.OUTPUT

while True:
    led.value = True
    time.sleep(0.5)
    led.value = False
    time.sleep(0.5)
```

**Comment by s-light** [comment]
thanks for the test and the merge!

you were a little to fast for me ;-)
i also did a blink test at the weekend and found the missing P1_25 ;-)
but did seem to forget to hit the 'Push' button after i committed....

i also added the non-GPIO Pins as comments - 
so its easier to reading the list and know what is what and spot mistakes..
i have redone this as a new merge request #102  (i think thats the cleanest way..)

**Pull request merged**
