### PR TITLE
Provide the use of Pine64 device on blinka with busio and digitalio

### PR DESCRIPTION
**Pull request by yeyeto2788**
In order to properly document (https://github.com/adafruit/circuitpython-org/pull/357) the addition of the board, thanks to @makermelissa for pointing the missing part of the addition in blinka.

Regards.

### CODE REVIEW

**Comment by makermelissa** [comment]
I'll give it a test here shortly.

**Comment by makermelissa** [comment]
Just a future note here, after struggling to install libgpiod like we have been on the Orange Pi, I realized that it's available via `sudo apt install`.

**Comment by makermelissa** [comment]
I have gone through and fixed a bunch of things and tested on the Pin64. You didn't have Allow Maintainers to edit checked, so I submitted a PR to your repo: https://github.com/yeyeto2788/Adafruit_Blinka/pull/1. Once you merge that in, it should update this PR.

**Comment by yeyeto2788** [comment]
Sorry for the inconveniences :cry: I'll keep it in mind for future PRs.

**Comment by makermelissa** [comment]
No problem. I ran the blinka test script (you can find in learn guides), which helped me find a bunch of things to fix, but I haven’t actually hooked up anything yet. You’ll need to make some board files for your other 2 boards and load them when appropriate. Use what I already did here as a template. I’d suggest that before working on the onion board for good practice.

**Comment by yeyeto2788** [comment]
Good to know, I started with the Onion one while I wait for the reviews but you're absolutely right. Better of finishing one thing before doing more things.

Also I just wanted to mention that we could easily add all Orange Pi (H3) board by just importing the `orangepipc.py` module into the other boards since they have the same chip and same pinout..

**Comment by makermelissa** [comment]
While you're probably right on the Orange Pi, we like to test them before putting them out as supported.

**Comment by yeyeto2788** [comment]
Sure! I'll look into my garage stuff for some boards I have from Orange pi which have H3 chip I hope they are the ones missing. 

If I find them what would be the best approach to test them? I want to test everything before doing any PR.

I'll wait for your instructions on next steps.

P.D: Sorry if it seems like I'm pushing things up, just want to help and make the use of blinka on different boards. My apologies for that.

**Comment by makermelissa** [comment]
No apologies necessary! Thanks for the push to add Blinka to more boards and all the effort you've been putting in!

**Comment by makermelissa** [comment]
Hey, I think we should merge this in so we can add the board to circuitpython.org and you can create a new PR for the additional boards.

**Comment by makermelissa** [comment]
@yeyeto2788, I went through and tested the Pine 64 and everything works, which is phenomenal.

**Pull request merged**
