### PR TITLE
pi 1 pin definitions

### PR DESCRIPTION
**Pull request by brennen**
Add correct pin definitions for two variants of Raspberry Pi 1.

### CODE REVIEW

**Comment by brennen** [comment]
@ladyada added rev2.

**Comment by ladyada** [comment]
kk is this ready to test?

**Comment by brennen** [comment]
should be!

**Comment by ladyada** [comment]
tested the v2, works!

**Comment by schustykd** [comment]
could someone advise if 26 pin raspi_1a is supported by blinka.

detect.py correctly identifies my board as RASPBERRY_PI_A but blinkatest.py fails with "Board not supported".

any advice is appreciated. sorry if this inquiry is in the wrong place - i'm new.

**Comment by ladyada** [comment]
please make a new issue!

**Pull request merged**
