### PR TITLE
usb_hid module

### PR DESCRIPTION
**Pull request by fivetide**
This PR is going to provide a usb_hid adapter using usb gadget. It is not yet complete, but i would like to collect early input on it.

- [x]  Add device class
- [x] usb_hid.disable() and usb_hid.enable()
- [x] can send reports
- [x] can receive reports (get_last_received_report)
- [x] sane descriptor for Device.KEYBOARD
- [x] sane descriptor for Device.MOUSE
- [x] sane descriptor for Devices.CONSUMER_CONTROL
- [x] boot device...?

### CODE REVIEW

**Comment by dhalbert** [comment]
The report descriptors we use in CircuitPython are here:
https://github.com/adafruit/circuitpython/blob/main/shared-module/usb_hid/Device.c

**Comment by fivetide** [comment]
So i was able to verify this works on a raspi zero wh with kmk firmware. Some things remain untested, like using multiple reports on one single device. 

What i did not grasp: Is the user supporsed to call usb_hid.enable manually, or would this have to be automated?

**Comment by makermelissa** [comment]
Based on https://learn.adafruit.com/customizing-usb-devices-in-circuitpython/hid-devices, I would say the user is supposed to call it manually.

**Comment by makermelissa** [comment]
The only thing is in circuitpython, it uses a boot.py file and we really don't have the equivalent in Blinka, so I think having it in the it manually enabled user script makes the most sense because many boards probably wouldn't support this.

**Review by makermelissa — APPROVED** [review]
Thank you for adding this. I know there are several folks who will appreciate this.

**Comment by makermelissa** [comment]
> what are prerequirements for this module on raspberry pi zero? Is there any example code?

I'm. not sure since I haven't run it. I think adding an example would be a good idea and this should be a new issue so it doesn't fall between the cracks.

**Pull request merged**
