### PR TITLE
To support pwm on ODROIDs

### PR DESCRIPTION
**Pull request by how2flow**
PlatformDetect:
- https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/333

### CODE REVIEW

**Comment by how2flow** [comment]
- https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/333
It seems that it's been two days since I left a comment, but there is no comment.
so I closed it

Anyway, This is a commit for support PWM on odroid boards.
Please review it.

Thanks.

**Comment by makermelissa** [comment]
Hi, I had taken some time off and have been swamped ever since I got back, so reviews might be taking a bit longer than usual until I'm caught up. Please have some patience. Thanks.

**Review by makermelissa — APPROVED** [review]
I ran pre-commit as ithat was needed to get past the checks failing. Looks good to me. Thanks for doing this.

**Comment by how2flow** [comment]
> Hi, I had taken some time off and have been swamped ever since I got back, so reviews might be taking a bit longer than usual until I'm caught up. Please have some patience. Thanks.

Thank you always for your hard work.

CircuitPython is a great platform.
But I only found out a month ago that I2C, SPI, PWM, etc. have not worked on Odroid for years in this good framework.
ODROID-M1 wasn't even working.

Well, not many people are using it, so I just found out,
but why don't many people use circuit python on Odroid?

Odroids are mainly used in certain products.
To be more loved for industrial or educational purposes, I thought it should be easier to control GPIO and various interfaces with C or Python.

We're almost there.
Odroid has 2 channels of ADC and none of them are working..

**Pull request merged**
