### PR TITLE
Enable support for multiple mcp2221

### PR DESCRIPTION
**Pull request by simallaire**
I am working on a project which requires the use of multiple MCP2221 + MLX90640 on a single host. It looked like it was not possible with the current code, so I made this example which shows how it can be accomplished without modifying any code of this library. You can then create different I2C objects independently, in my case MLX90640, and use them normally.

- Redefine existing classes to be able to connect with device path
- Use MCP2221 which is created on import.
- Connect to other MCP2221, if any.
- Print ids (made for mlx90640)

### CODE REVIEW

**Comment by makermelissa** [comment]
It looks like you need to run black on your code.

**Comment by makermelissa** [comment]
For PylLint, you can add `# pylint: disable=too-few-public-methods` to those classes.

**Review by makermelissa — APPROVED** [review]
Thanks for adding this.

**Comment by caternuson** [comment]
@simallaire If you want, you could also open an issue to request this general support be added to Blinka. I thought there already was one, but not seeing it. There's already an issue for multiple FT232H's:
https://github.com/adafruit/Adafruit_Blinka/issues/260
Just realize it may take some time, as there are lots of details to deal with, similar to all the discussion in the above thread.

**Pull request merged**
