### PR TITLE
Add 'deinit()' Function To PWMOut

### LINKED ISSUE #120: Add Deinit method to PWMOut for Travis
Travis uses Blinka, so pylint'ing libraries requiring `PWMOut` fails on `no-member` since Blinka's `PWMOut` class does not have the `deinit` method in the CircuitPython API (https://circuitpython.readthedocs.io/en/4.x/shared-bindings/pulseio/PWMOut.html#pulseio.PWMOut.deinit).

@ladyada  would a `deinit()` method be similar to `close()`? https://github.com/adafruit/Adafruit_Blinka/blob/master/src/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py#L107

Travis log: https://travis-ci.com/brentru/CircuitPython_RGBLED/builds/113806920#L277

### PR DESCRIPTION
**Pull request by sommersoft**
Fixes #120.

I cannot test this, since `pulseio.PWMOut` is only available for the Google Coral and Giant Board. Neither of which I have.

### CODE REVIEW

**Comment by brentru** [comment]
@sommersoft While this works, calling `.frequency` or any other getter on a de-init'd pwm object returns

```
>>> led.frequency
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 227, in _get_frequency
    return 1.0 / self._get_period()
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 149, in _get_period
    period_ns = int(self._read_pin_attr(self._pin_period_path))
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 142, in _read_pin_attr
    with open(path, 'r') as f_attr:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/pwm/pwmchipNone/pwmNone/period'
```

Instead, we should throw something like the following on a call for de-initialize pwm object property:

```
>>> pwm.frequency
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Object has been deinitialized and can no longer be used. Create a new object.
```

**Comment by brentru** [comment]
@sommersoft  I implemented a nicer error here which checks if the`_pwmpin` is `None`, since that's set in `close()`
https://github.com/brentru/Adafruit_Blinka/commit/2fb1040add181fde935cad747041ecf08871af3e

Code in there reflects latest master (I pulled a fix in this AM, this PR has a conflict) and has been tested on a Google Coral 

Output of init'ing, deinit'ing, and calling properties.
```
>>> led = pulseio.PWMOut(board.PWM3, frequency=5000, duty_cycle=0)
>>> led.frequency
5000.0
>>> led.deinit()
>>> led.frequency
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 230, in _get_frequency
    return 1.0 / self._get_period()
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 149, in _get_period
    raise ValueError('Object has been deinitialized and can no longer be used. Create a new object.')
ValueError: Object has been deinitialized and can no longer be used. Create a new object.
>>> led.duty_cycle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 186, in _get_duty_cycle
    raise ValueError('Object has been deinitialized and can no longer be used. Create a new object.')
ValueError: Object has been deinitialized and can no longer be used. Create a new object.
```

**Comment by sommersoft** [comment]
@brentru I can handle the conflict; easy peasie. Do you want me to add in the `deinit()` check, or would you rather submit a secondary PR for it?

**Comment by brentru** [comment]
@sommersoft Let's add the deinit check in this PR while we're at it, then I'll do a release with this and the previous pwm fix

**Comment by sommersoft** [comment]
alrighty. it'll be up in a couple minutes.

**Comment by brentru** [comment]
This fix chains the exception output,

```
ValueError: Object has been deinitialize and can no longer be used. Create a new object.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 235, in _get_frequency
    return 1.0 / self._get_period()
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 159, in _get_period
    raise PWMError(None, "Unknown period value: \"%s\"" % period_ns)
```

**Comment by brentru** [comment]
Tested on my end, it's not chaining `ValueErrors` anymore. Thanks for the PR!

**Comment by tannewt** [comment]
@brentru Thanks for releasing this PR! Unfortunately, it should have bumped the major version number so it is 2.0.0 because `close` was removed and is therefore not backwards compatible.

**Comment by brentru** [comment]
@tannewt  Ok - could I delete 1.3.4 and re-release as 2.0.0?

**Comment by tannewt** [comment]
Just leave 1.3.4 and add 2.0.0.

**Comment by brentru** [comment]
Added 2.0.0: https://github.com/adafruit/Adafruit_Blinka/releases/tag/2.0.0

**Pull request merged**
