### PR TITLE
Add support for Jetson Orin

### PR DESCRIPTION
**Pull request by anhmiuhv**

### CODE REVIEW

**Comment by makermelissa** [comment]
Hi, thanks for submitting this. It looks like it's failing a few checks. Would you mind fixing these? Here's a guide that might help: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code

Here's the error page (you can get to it by clicking the red X and then details): https://github.com/adafruit/Adafruit_Blinka/runs/7513913372?check_suite_focus=true

For the Black errors, running pre-commit and pushing should fix the errors. 
For the Reuse licensing, you should just be able to copy the headers from some other files.
For the PyLint errors, just try following the suggestions on the error page.

**Comment by anhmiuhv** [comment]
Ok I see

**Comment by anhmiuhv** [comment]
Ready for review

**Review by makermelissa — APPROVED** [review]
Looks good to me. Thanks for adding.

**Pull request merged**
