### PR TITLE
Enable setting no_cs in case a board does support it

### PR DESCRIPTION
**Pull request by makermelissa**
When trying to fix the RA8875, I noticed it wasn't even trying to set no_cs, so this at least tries.

### CODE REVIEW

**Comment by ladyada** [comment]
hi im pretty sure this does not work and was causing kernel complaints which is why we removed it. does it work on a pi?

**Comment by makermelissa** [comment]
Yeah, I tested it on the Pi. Maybe using the original spidev driver was causing errors.

**Comment by ladyada** [comment]
and the CS line doesnt toggle?

**Comment by makermelissa** [comment]
No, it's still toggling on the Pi. We can just close this if you think it's not worth it. I was just thinking it might work on other boards, but now that you mention it, it also might cause problems on other boards.

**Comment by ladyada** [comment]
it will cause problems, and i dont like promising it - lets drop it

**Pull request closed without merging**
