### PR TITLE
Close HID connnection to MCP2221 when resetting

### PR DESCRIPTION
**Pull request by caternuson**
Fix for #573.

Pretty simple, just need to explicitly close when resetting. Tested locally to recreate original issue and verify this patch worked to fix. Even blinked an LED to make sure.

### CODE REVIEW

**Comment by caternuson** [comment]
Oh, wait a sec. There's U2IF also. Will check that and push some more updates.

**Comment by caternuson** [comment]
Yep. Same thing happens with U2IF. Also get the "already open" error. Used a Feather RP2040 to verify. Closing fixes there as well. Blinked #13 led to verify.

**Review by ladyada — APPROVED** [review]
nice find

**Comment by caternuson** [comment]
thanks. wasn't me:
https://github.com/adafruit/Adafruit_Blinka/issues/573#issuecomment-1098404088

**Pull request merged**
